"""Initial migration

Revision ID: 279306f5fd8d
Revises: 
Create Date: 2025-11-14 18:15:30.131450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279306f5fd8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_nickname'), ['nickname'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('roles_players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'role_id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tournament_date', sa.Date(), nullable=False),
    sa.Column('buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_tournament_date'), ['tournament_date'], unique=False)

    op.create_table('tournament_player',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('posizione', sa.Integer(), nullable=True),
    sa.Column('rebuy', sa.Integer(), nullable=False),
    sa.Column('rebuy_total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prize', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id'),
    sqlite_autoincrement=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_player')
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_tournament_date'))
        batch_op.drop_index(batch_op.f('ix_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_tournament_admin_id'))

    op.drop_table('tournament')
    op.drop_table('roles_players')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_nickname'))
        batch_op.drop_index(batch_op.f('ix_player_email'))

    op.drop_table('player')
    # ### end Alembic commands ###
